name: "Analyze Codes"

on:
    push:
        branches: ["master", "dev"]
    pull_request:
        branches: ["master", "dev"]
    workflow_dispatch:

jobs:
    analyze:
        name: Analyze Codes
        runs-on: "ubuntu-latest"
        permissions:
            actions: read
            contents: read
            security-events: write

        strategy:
            fail-fast: false
            matrix:
                language: ["javascript"]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v2
              with:
                  languages: ${{ matrix.language }}
                  queries: "security-and-quality"

            - name: Install Dependencies
              run: |
                  npm install

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v2
              with:
                  category: "/language:${{matrix.language}}"

            - name: Run ESLint
              run: npx eslint .
                  --config .eslintrc.js
                  --ext .js,.jsx,.ts,.tsx
                  --format @microsoft/eslint-formatter-sarif
                  --output-file eslint-results.sarif
              continue-on-error: true

            - name: Run StyleLint
              run: npx stylelint "**/*.{css,scss}"

            - name: Upload analysis results to GitHub
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: eslint-results.sarif
                  wait-for-processing: true
