name: Review Dependency
on:
    pull_request:
        branches: ["master", "dev"]

permissions:
    contents: read

jobs:
    dependency-review:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v3

            - name: "Review Dependency"
              uses: actions/dependency-review-action@v3
